### ISSUE TITLE
Integrate Sensors & flash drivers

### ISSUE THREAD

**Issue by elsalahy** [TheThingsIndustries/generic-node-se#37]
**Summary:** 

Integrate the drivers of these components into our repo.

- [x] Tracer (with UART)
- [x] SHTC3 (with I2C1)
- [x] LIS2DH12 (with I2C1)
- [ ] ATECC608A (with I2C2)
- [x] MX25R1635 (with SPI)
- [ ] SX1262 (with SPI)

**Why do we need this?**

To be able to build applications that use these components.

**What is already there? What do you see now?**

- Tracer (with UART) in #32 
- SHTC3 (with I2C1) in #34 

**What is missing? What do you want to see?**

The rest

**How do you propose to implement this?**

Most of the components have a relevant open source driver, and it should be integrated with our repository and tested for functionality.

**Environment:**

Bare-metal

**Acceptance Criteria:**

The application can control the several components.
 
**What can you do yourself and what do you need help with?**

ALL
