### ISSUE TITLE
basic FUOTA

### ISSUE THREAD

**Issue by elsalahy** [TheThingsIndustries/generic-node-se#69]
**Summary:** 

A FUOTA feature will be a great addition to the set of available applications.

**Why do we need this?**

A critical system and LoRaWAN feature that will allow for the adaption of the device and showcases the potential of LoRaWAN.

**What is already there? What do you see now?**

- Example implementation for the older generic node.
- ST FUOTA demo 

**What is missing? What do you want to see?**

An implementation of a device specific FUOTA demo.

**How do you propose to implement this?**

- [x] Implement a basic bootloader
- [x] Implement a LoRaWAN node update client
- [x] Implement a server side LoRaWAN update client

**Environment:**

BareMetal

**Acceptance Criteria:**

- Compatible with LoRaWAN specs

**What can you do yourself and what do you need help with?**

All
