### ISSUE TITLE
basic verification and validation of v1.1 HW and FW 

### ISSUE THREAD

**Issue by elsalahy** [TheThingsIndustries/generic-node-se#95]
**Summary:** 

Umbrella issue for testing, verifying and validating the new v0.2 HW and relevant FW.
Tasks:
- [x] Improve basic apps to reflect and test the new HW changes
- [x] Ensure any HW/FW design change is reflected in the documentation
- [x] Flash and run all basic apps and verify functionality
- [x] Validate power consumption of each app
- [x] Ensure MCU RTC and timers are precise
- [ ] Test antenna performance and ensure usable performance (compare to v0.1)
- [ ] Add more relevant issues/tasks here

**Why do we need this?**

To ensure the new board HW and FW is usable.

**What is already there? What do you see now?**

Working and tested FW on the v0.1 HW.

**What is missing? What do you want to see?**

Basic testing of the HW/FW functionality.

**How do you propose to implement this?**

Umbrella issue, can open more issues with relevant details

**Environment:**

Bare-metal and FreeRTOS

**Acceptance Criteria:**

Report on the new HW performance.

**What can you do yourself and what do you need help with?**

All

**Comment by elsalahy** [comment]
We received the 2nd iteration of the HW on 18th of Jan.
We validated the device functionality using basic apps and the results are below:
- `basic`  ✅  (some nodes failed to pass, need to investigate the production issue)
- `basic_lorawan` ✅  (The RSSI and the antenna performance need to be validated)

**Comment by azerimaker** [comment]
Basic verification of **v1.1** HW is now complete.  
Out of 99 beta boards (1x was incomplete from the PCBA) 84 passed the basic test, and only 80 of them have passed the LoRaWAN test at first pass. 4 of them gets stuck at LoRaWAN app. 
This results in 81% of overall yield. 
Rest of the 15 boards won't start at all (Buck-Boost goes into protection mode). I've investigated the issue and in most of them it comes down to the poor soldering of the buck-boost converter's WLCSP-20 package (BGA). Please see the related issue #36 for more details. 

![yield](https://user-images.githubusercontent.com/2662257/111037869-4c614980-8426-11eb-9552-16efc423d5ec.PNG)

**Comment by elsalahy** [comment]
Yeah indeed basic verification is done.
Relevant advanced issues  #128 #36
