### ISSUE TITLE
FreeRTOS-LoRaWAN integration

### ISSUE THREAD

**Issue by elsalahy** [TheThingsIndustries/generic-node-se#99]
**Summary:** 

Umbrella issue for improving LoRaWAN FreeRTOS integration.
- [ ] Enable Tickless_IDLE mode and measure power consumption, see #84
- [x] Reduce logging overhead, see #90
- [x] Use MAC layer in delays `DutyCycleWaitTime ` after update to v1.0, see #88 
- [ ] Integrate RTC with LW FreeRTOS app, see #100
